options(stringsAsFactors = FALSE)
repo <- normalizePath(file.path(dirname(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1])), ".."), winslash = "/", mustWork = TRUE)
a <- read.delim(file.path(repo, "outputs/02_GSE118761/projection/GSE118761_projection_assignments_FINAL.tsv"), check.names = FALSE)
stopifnot(nrow(a) == 104L, !anyDuplicated(a$sample_id))
stopifnot(sum(a$tissue == "nasal") == 55L, sum(a$tissue == "tracheal") == 49L)
observed <- with(a, table(tissue, factor(assigned_state, levels = c("E1", "E2", "E3"))))
stopifnot(identical(as.integer(observed["nasal", ]), c(21L, 27L, 7L)))
stopifnot(identical(as.integer(observed["tracheal", ]), c(21L, 23L, 5L)))
cat("PASS: GSE118761 sample counts and projection counts\n")
