codex_r_helper <- Sys.getenv("CODEX_R_LIB_HELPER", "")
if (nzchar(codex_r_helper) && file.exists(codex_r_helper)) source(codex_r_helper)
options(stringsAsFactors = FALSE)
repo <- normalizePath(file.path(dirname(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1])), ".."), winslash = "/", mustWork = TRUE)
if (!requireNamespace("yaml", quietly = TRUE)) stop("Package yaml is required")
cfg <- yaml::read_yaml(file.path(repo, "config/GSE118761_projection_final.yaml"))
out <- file.path(repo, cfg$outputs$projection_dir)
a <- read.delim(file.path(out, "GSE118761_projection_assignments_FINAL.tsv"), check.names = FALSE)
c <- read.delim(file.path(out, "GSE118761_projection_counts_FINAL.tsv"), check.names = FALSE)
d <- read.delim(file.path(out, "GSE118761_projection_distances.tsv"), check.names = FALSE)
stopifnot(nrow(a) == 104L, sum(a$tissue == "nasal") == 55L, sum(a$tissue == "tracheal") == 49L)
stopifnot(!anyDuplicated(a$sample_id), identical(a$sample_id, d$sample_id))
rederived <- c("E1", "E2", "E3")[max.col(-as.matrix(d[, c("distance_to_E1", "distance_to_E2", "distance_to_E3")]), ties.method = "first")]
stopifnot(identical(a$assigned_state, rederived))
for (i in seq_len(nrow(c))) stopifnot(c$n[i] == as.integer(cfg$expected_projection_counts[[c$tissue[i]]][[c$state[i]]]))
stopifnot(file.exists(file.path(repo, "figures/Figure5/Figure5f_source_data.tsv")))
stopifnot(file.exists(file.path(repo, "tables/Supplementary_Table_S9_source.tsv")))
cat("PASS: GSE118761 projection is sample-level, executable, and matches the locked final config\n")
