options(stringsAsFactors = FALSE)
repo <- normalizePath(file.path(dirname(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value=TRUE)[1])), "../.."), winslash="/", mustWork=TRUE)
source(file.path(repo,"R/common/module_scoring.R"))
a <- readRDS(file.path(repo,"outputs/03_GSE152004/GSE152004_aligned_input.rds"))
t2 <- score_mean_gene_z(a$expr,c("CST1","CLCA1","SERPINB2"),min_present=3)
cut <- median(t2)
out <- data.frame(sample_id=a$metadata$sample_id,T2_score_vst_gene_z=t2,T2_high=as.integer(t2>=cut),median_threshold=cut)
stopifnot(sum(out$T2_high)==348L,sum(out$T2_high==0L)==347L)
write.csv(out,file.path(repo,"outputs/03_GSE152004/GSE152004_T2_definition_recomputed.csv"),row.names=FALSE)
