options(stringsAsFactors = FALSE)
repo <- normalizePath(file.path(dirname(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value=TRUE)[1])), "../.."), winslash="/", mustWork=TRUE)
d <- read.csv(file.path(repo,"outputs/03_GSE152004/GSE152004_module_scores_recomputed.csv"),check.names=FALSE)
fit <- lm(repair_ECM_z~T2_z+IFN_z,data=d)
d$repair_ECM_resid <- as.numeric(scale(residuals(fit)))
assoc <- glm(T2_high~repair_ECM_resid+IFN_z,data=d,family=binomial())
sm <- coef(summary(assoc)); ci <- confint.default(assoc,"repair_ECM_resid")
out <- data.frame(R2=summary(fit)$r.squared,residual_variance_retained=1-summary(fit)$r.squared,OR=exp(coef(assoc)["repair_ECM_resid"]),CI_low=exp(ci[1]),CI_high=exp(ci[2]),p_value=sm["repair_ECM_resid","Pr(>|z|)"])
write.csv(out,file.path(repo,"outputs/03_GSE152004/GSE152004_residualization_recomputed.csv"),row.names=FALSE)
